# Generated by Django 4.1 on 2022-08-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='Country',
            field=models.CharField(blank=True, default='India', max_length=20),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='college',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='facebook_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='instagram_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='interest',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='phone_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='portfolio',
            field=models.URLField(blank=True, default=''),
        ),
    ]
