# Generated by Django 4.1 on 2022-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_studentuser_country_studentuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
