# Generated by Django 4.1 on 2022-09-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_rename_country_studentuser_country'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
